remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Creativity Partners
logo: https://7pub.gitproxy.run/logo.svg
description: Terrible Reason
show_downloads: true
theme: jekyll-theme-minimal
favicon: https://7pub.gitproxy.run/static/favicon/favicon.ico